### ISSUE TITLE
Having trouble with running :TestNearest

### ISSUE THREAD

**Issue by mauchchhash** [janko/vim-test#403]
I am having trouble with running the TestNearest command in one of my Laravel projects with phpunit. The other commands (TestSuite, TestFile, TestLast, TestVisit) are working just fine. But the TestNearest Is not working. I place my cursor inside a test funtion and run the TestNearest trigger and the following error is displayed:
`/home/mahim/work/coranks/tests/Feature/ExampleTest.php:1
(function (exports, require, module, __filename, __dirname) { <?php
^

SyntaxError: Unexpected token <
at createScript (vm.js:80:10)
at Object.runInThisContext (vm.js:139:10)
at Module._compile (module.js:616:28)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
at Function.Module.runMain (module.js:693:10)
at startup (bootstrap_node.js:188:16)
at bootstrap_node.js:609:3
I tested it on a fresh laravel project and theTestNearestcommand is working there fine. So reset the the test file of my main project to how it was when I first installed laravel. Hear's how it looks now:<?php

namespace Tests\Unit;

use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class ExampleTest extends TestCase
{
/**
* A basic test example.
*
* @return void
*/
public function testBasicTest()
{
$this->assertTrue(true);
}
}
`

As you can see. There is nothing fancy here. It looks exactly like the test on the fresh laravel project I ran(where theTestNearest trigger is working)...

**Edit:** If I run the command with :TestNearest, then it works. But It doen't work with the keymapping/trigger key(my keymapping: nmap <silent> <leader>tn :TestNearest<CR>)
When I restart vim then it works(both :TestNeaerset and the key trigger) but after sometime the keymapping stops working again..

**Comment by mauchchhash** [comment]
This is odd. Now I see that the `TestNearest` command is working fine everytime. I think you should delete this issue.
